name: Build mockserver multi-arch image if needed
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build-new-image-if-needed:
    runs-on: ubuntu-latest
    env:
      TAG_TO_PUSH: ''
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: octokit/request-action@v2.x
        id: get_mockserver_tags
        with:
          route: GET /repos/mock-server/mockserver/tags
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        id: get_dennisameling_tags
        with:
          route: GET /repos/dennisameling/mockserver/tags
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for new tags, update master if necessary, publish tag
        id: check_for_new_version
        
        run: |
          LATEST_TAG_MOCKSERVER=$(jq -n --raw-output '${{ steps.get_mockserver_tags.outputs.data }} | .[0].name')
          echo "Latest tag on mock-server/mockserver: ${LATEST_TAG_MOCKSERVER}"

          LATEST_TAG_DENNISAMELING=$(jq -n --raw-output '${{ steps.get_dennisameling_tags.outputs.data }} | .[0].name')
          echo "Latest tag on dennisameling/mockserver: ${LATEST_TAG_DENNISAMELING}"

          if [[ "${LATEST_TAG_MOCKSERVER}" == "${LATEST_TAG_DENNISAMELING}" ]]; then
            echo "Latest tag already found on dennisameling/mockserver. Won't build."
            exit 0
          fi

          echo "Latest tag ${LATEST_TAG_MOCKSERVER} not found yet in dennisameling/mockserver. Building now."

          echo "Updating master branch through a git merge..."
          git remote add upstream https://github.com/mock-server/mockserver
          git fetch upstream
          git merge upstream/master
          git push

          echo "Creating tag ${LATEST_TAG_MOCKSERVER}-multi-arch..."
          git tag ${LATEST_TAG_MOCKSERVER}-multi-arch
          git push origin ${LATEST_TAG_MOCKSERVER}-multi-arch

          echo "Will build new docker image!"
          echo "TAG_TO_PUSH=${LATEST_TAG_MOCKSERVER}" >> $GITHUB_ENV

      - name: Set up QEMU
        if: env.TAG_TO_PUSH != ''
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: env.TAG_TO_PUSH != ''
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: env.TAG_TO_PUSH != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: env.TAG_TO_PUSH != ''
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dennisameling/mockserver:latest,dennisameling/mockserver:${{ env.TAG_TO_PUSH }}
